name: Zip Resource Pack

on:
  push:
    branches:
      - master

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zip Datapack
        run: |
          zip -r "Enhanced Fonts.zip" pack.mcmeta pack.png assets/

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Enhanced Fonts
          path: "Enhanced Fonts.zip"